### ISSUE TITLE
Return offset

### ISSUE THREAD

**Issue by yanzhang0417** [mvirgo/MLND-Capstone#19]
Hi Michael. Thank you so much for this intensive work! I wonder in your final method, is there any way that could calculate the offset of the car from lanes, comparing with the method that uses perspective transformation?

**Comment by yanzhang0417** [comment]
Sorry for disturbing again. I am a newbie to ML field. Hope here is the right place for asking some questions.  I noticed that you label current lane by G channel.  For the fully CNN model, if it calculate by the intensity of each pixel, how does it identify that targeted lane instead of treating the opposite lane or adjacent lane as the target as well? Thanks in advance!

**Comment by mvirgo** [comment]
Hi there! There is not a built in method to do so, but my guess would be that you could estimate it based off of where the car is in comparison to the edges of the pixels making up the lane, just partway up the image (probably about 10-20% up the image). You could then find where the middle of the lane's edges were per the detection, and compare it to the middle of the image (assuming the camera is mounted in the middle of the car).

For the fully CNN model, it has essentially just learned only to look at its own lane because the training labels are done that way. You could potentially label the other lanes differently if you wanted to also separately select them, although it's most typical to only detect the whole road as one class (see the [Kitti road dataset](http://www.cvlibs.net/datasets/kitti/eval_road.php) for instance).

**Comment by yanzhang0417** [comment]
Hi Michael, thanks for your reply. Actually I tried your model with Kitti road data (with only single current lane labeled). There are a lot of cases (actually most cases) that the model could not identify current lane correctly, either not matching current lane or identifying the adjacent lane as the target too. Do you have any idea about why this happens? Is it because the model hasn't been trained with urban road (almost all the kitti data are urban road) yet? Thanks!

**Comment by mvirgo** [comment]
Yes, pretty much. The model was only trained with two different cameras (the one used in Udacity's dataset and from my own camera), plus it was based on only roads with clear yellow and white markings, without things like parked cars and such in the way.
