### ISSUE TITLE
Certain files not found 

### ISSUE THREAD

**Issue by keerthishan123** [mvirgo/MLND-Capstone#38]
Can you provide images of dataset?

**Comment by mvirgo** [comment]
The early steps is just there more to be able to look at - unfortunately most of the original files have since been deleted, since they aren't a part of the final project. I also don't have all that well documented what the original order was, outside of high level details in the [related Medium post](https://towardsdatascience.com/lane-detection-with-deep-learning-part-1-9e096f3320b7). That could potentially be put back together from the git commit history, but probably more work than it is worth.
