### ISSUE TITLE
Which .py file outputs scaler.p?

### ISSUE THREAD

**Issue by Navaneeth-krishnan** [mvirgo/MLND-Capstone#5]
where do I get scaler.p from to reverse label normalization?

**Comment by mvirgo** [comment]
I just re-added [combine_and_normal_old.py](https://github.com/mvirgo/MLND-Capstone/blob/master/combine_and_normal_old.py) that does this, assuming you are using the coefficient labels and not the lane image labels. Please note that you need to use the scaler again on the output of the neural network in order to get back to the correct values.
