### ISSUE TITLE
What are coefficient labels related to?

### ISSUE THREAD

**Issue by zj040045** [mvirgo/MLND-Capstone#6]
I drew coefficient labels as curves on the downsized pictures and I found that curves can not match lanes. What are these labels related to?

**Comment by mvirgo** [comment]
A few things might help:
1) Have the images been calibrated for your camera? If not, that could make a difference due to the distortion effects of different camera.
2) Did you come up with a perspective transformation that works for your camera? This needs manual tuning based on where the lanes are and where the horizon is.
3) Did you check if the color/gradient thresholds you are using actually work on your road images? I re-drew over the lane lines in red in mine specifically so that a 'R' color threshold would only detect the lines, but if you are using regular images this needs to be manually tuned.

The main purpose of using the eventual fully convolutional network was that it avoided a lot of the issues with the above that are very specific to the camera and lighting. Let me know if this helps at all or if you have some more questions.

**Comment by mvirgo** [comment]
Any follow-up questions to this? I will close soon otherwise.

**Comment by zj040045** [comment]
No, thank you for your answer. It helps me a lot.
