### ISSUE TITLE
Any Idea for the use DC motors or etc for that?

### ISSUE THREAD

**Issue by mustafamerttunali** [mvirgo/MLND-Capstone#7]
Hello. First, cong. Awesome project, I was wanting to learn deep learning with making lane detection. I can learn now but how can I control the motors sir? How  we can  calculate the lanes? I have idea with using Tan90=Sin90/Cos90 like that. 

Have a nice day!

**Comment by mvirgo** [comment]
Thanks! I'm not as well versed on the robotics side of things as far as controlling the motors go, although ROS is something I'm starting to work in. For calculating the lanes, are you looking at it related to curvature, where the car is in the lane, etc.?

**Comment by mustafamerttunali** [comment]
I have 2 DC motor.  If lane goes left  it must be like this:
Left:255-off center Right:255

I can control the motor now with using 255-off center but of the lane goes the right, the information of the off center is wrong. I need off center like this:

If lane goes left: - off center
If lane goes right: + off center
if lane goes straight: 0

Like this sir. I made  but the calculate is wrong I think. Because when the lane goes straight, off center is 7cm or 9. 

What kind of way should I use sir?

Have a nice day.

**Comment by mvirgo** [comment]
That's a tough one - I'm not sure on the best way to calculate the center of the lane. Is this getting calculated from a camera image or similar? If so it could just be that it is already a little off center. It sounds like you otherwise have a decent plan if you can fix that issue, but you could also look at PID control for making turns and such if you have the ground truth center figured out.

**Comment by mvirgo** [comment]
Closing since it looks like there's no further follow-ups.
