### ISSUE TITLE
Samples issue

### ISSUE THREAD

**Issue by yuhenry** [mvirgo/MLND-Capstone#9]
Well-done job.  I'm longing to know something about samples preparation.
Could you show some original images and labels which were not converted to *.p format?
Furthermore, How to convert my data to *.p format?
THX.

**Comment by huazai-1994** [comment]
i have the same question as the previous person.could you please show me some tips to mark the train_data?thanks

**Comment by mvirgo** [comment]
You should still be able to see the original images and labels (although a little smaller size) from the pickle files. Do the following:
```
import pickle
import matplotlib.pyplot as plt

images = pickle.load(open( "full_CNN_train.p", "rb" ))
plt.imshow(images[0])
plt.show()
```
Note that the above will work only the training images. You can replace the **0** index on `images` in `plt.imshow()` with whichever image you want to view.

For the labels, since they are only the single green channel, you could either stack them with empty arrays to make a depth of three (i.e. RGB with the label the middle in the stack), or just use `np.squeeze` to get rid of the last dimension, and then use `plt.imshow()` on a given image, although this will look black and white.
